// i18nextract lists Nacomline's texts to translate (same format as Matriline's):
//
//	go run ./i18nextract            writes lang/strings.txt and lang/nacomline.conf (English)
//	go run ./i18nextract -check es  lists what lang/es.txt lacks, and whether
//	                                lang/nacomline.conf.es translates the current template
//
// A text is to be translated when the code passes it to T or Tf, and the usage text.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	check := flag.String("check", "", "compare lang/<code>.txt and lang/nacomline.conf.<code> with the code")
	flag.Parse()
	var texts []string
	where := map[string]string{}
	tmpl := ""
	fset := token.NewFileSet()
	files, _ := filepath.Glob("*.go")
	sort.Strings(files)
	for _, f := range files {
		if strings.HasSuffix(f, "_test.go") {
			continue
		}
		af, err := parser.ParseFile(fset, f, nil, 0)
		if err != nil {
			fail(err)
		}
		lit := func(e ast.Expr) (string, bool) {
			b, ok := e.(*ast.BasicLit)
			if !ok || b.Kind != token.STRING {
				return "", false
			}
			s, err := strconv.Unquote(b.Value)
			return s, err == nil
		}
		add := func(s string, n ast.Node) {
			if s != "" && where[s] == "" {
				p := fset.Position(n.Pos())
				where[s] = fmt.Sprintf("%s:%d", p.Filename, p.Line)
				texts = append(texts, s)
			}
		}
		ast.Inspect(af, func(n ast.Node) bool {
			switch x := n.(type) {
			case *ast.CallExpr:
				if id, ok := x.Fun.(*ast.Ident); ok && (id.Name == "T" || id.Name == "Tf") && len(x.Args) > 0 {
					if s, ok := lit(x.Args[0]); ok {
						add(s, x)
					}
				}
			case *ast.ValueSpec:
				for i, id := range x.Names {
					if i < len(x.Values) {
						if s, ok := lit(x.Values[i]); ok {
							switch id.Name {
							case "usage":
								add(s, x)
							case "defaultConf":
								tmpl = s
							}
						}
					}
				}
			}
			return true
		})
	}
	sum := sha256.Sum256([]byte(tmpl))
	source := "# source " + hex.EncodeToString(sum[:8])
	if *check != "" {
		have := map[string]bool{}
		if b, err := os.ReadFile("lang/" + *check + ".txt"); err == nil {
			var cur string
			for _, l := range strings.Split(string(b), "\n") {
				if v, ok := strings.CutPrefix(l, "en: "); ok {
					cur = v
				} else if v, ok := strings.CutPrefix(l, "  |"); ok && cur != "" && !have[cur] {
					cur += "\n" + v
				} else if v, ok := strings.CutPrefix(l, *check+": "); ok && v != "" {
					have[cur] = true
				}
			}
		}
		n := 0
		for _, t := range texts {
			if !have[t] {
				fmt.Printf("missing (%s): %q\n", where[t], t)
				n++
			}
		}
		fmt.Printf("%d texts, %d without a translation\n", len(texts), n)
		if b, err := os.ReadFile("lang/nacomline.conf." + *check); err != nil {
			fmt.Printf("nacomline.conf.%s: missing (first line %q)\n", *check, source)
		} else if first, _, _ := strings.Cut(string(b), "\n"); first != source {
			fmt.Printf("nacomline.conf.%s: translates an older template (%s; now %s)\n", *check, first, source)
		} else {
			fmt.Printf("nacomline.conf.%s: current\n", *check)
		}
		return
	}
	var b strings.Builder
	b.WriteString(`# Texts to translate (generated by: go run ./i18nextract; do not edit by hand).
# Copy this file to <code>.txt and write each translation after "<code>:" (e.g. "es:").
# Same rules as Matriline's: keep %s %d %q %v exactly and in order; keep commands, options,
# file names and anything inside quotes in English; "  |" continues a text on a new line;
# keep the usage text's columns (help <command> finds a command at 2 spaces).

`)
	for _, t := range texts {
		lines := strings.Split(t, "\n")
		fmt.Fprintf(&b, "# %s\nen: %s\n", where[t], lines[0])
		for _, l := range lines[1:] {
			fmt.Fprintf(&b, "  |%s\n", l)
		}
		b.WriteString("es:\n\n")
	}
	if err := os.WriteFile("lang/strings.txt", []byte(b.String()), 0o644); err != nil {
		fail(err)
	}
	if err := os.WriteFile("lang/nacomline.conf", []byte(tmpl), 0o644); err != nil {
		fail(err)
	}
	fmt.Printf("%d texts written to lang/strings.txt; template to lang/nacomline.conf (%s)\n", len(texts), source)
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "i18nextract:", err)
	os.Exit(1)
}
